# Generated by Django 3.2.8 on 2021-10-29 13:03

import django.contrib.auth.models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCount',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика по пользователям',
                'verbose_name_plural': 'Статистика по пользователям',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agreement',
            field=models.BooleanField(default=True, validators=[users.models.validate_agreement], verbose_name='Согласие на обработку персональных даных'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
