# Generated by Django 3.2.8 on 2021-11-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20211102_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatistics',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
    ]
