# Generated by Django 3.2.8 on 2021-10-26 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_on_cake', models.CharField(blank=True, max_length=200, verbose_name='надпись на торте')),
                ('berry', models.ManyToManyField(to='shop.Berry', verbose_name='ягоды')),
            ],
        ),
        migrations.CreateModel(
            name='CakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CakeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заявка обрабатывается'), (2, 'Торт готовится'), (3, 'Торт в пути'), (4, 'Торт доставлен'), (5, 'Заказ отменен')], db_index=True, default=1, verbose_name='статус заказа')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('destination', models.CharField(max_length=200)),
                ('delivery_time', models.DateTimeField()),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cake', verbose_name='торт')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий пользователя')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='отмененный заказ')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ManyToManyField(to='shop.Decor', verbose_name='декор'),
        ),
        migrations.AddField(
            model_name='cake',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cakelevel', verbose_name='уровень'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ManyToManyField(to='shop.Topping', verbose_name='топпинги'),
        ),
    ]
