# Generated by Django 3.2.8 on 2021-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211029_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationOrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика отмененных заказов',
                'verbose_name_plural': 'Статистика отмененных заказов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.cancellationorder',),
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика по статусам заказов',
                'verbose_name_plural': 'Статистика по статусам заказов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.AlterModelOptions(
            name='berry',
            options={'ordering': ('price',), 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='cakeform',
            options={'ordering': ('price',), 'verbose_name_plural': 'Формы тортов'},
        ),
        migrations.AlterModelOptions(
            name='cakelevel',
            options={'ordering': ('price',), 'verbose_name_plural': 'Уровни тортов'},
        ),
        migrations.AlterModelOptions(
            name='cancellationorder',
            options={'verbose_name_plural': 'Отмены заказов'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'ordering': ('price',), 'verbose_name_plural': 'Декоры'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ('price',), 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AlterField(
            model_name='cake',
            name='caption_on_cake',
            field=models.CharField(blank=True, max_length=45, verbose_name='надпись на торте'),
        ),
    ]
